#!/bin/bash
# Exit immediately if a command exits with a non-zero status.
set -e

# Define the build directories
FFMPEG=$(pwd)

# Install system dependencies
sudo apt-get update -qq
sudo apt-get -y install \
  autoconf \
  automake \
  build-essential \
  cmake \
  git-core \
  libass-dev \
  libfreetype6-dev \
  libgnutls28-dev \
  libmp3lame-dev \
  libsdl2-dev \
  libtool \
  libva-dev \
  libvdpau-dev \
  libvorbis-dev \
  libxcb1-dev \
  libxcb-shm0-dev \
  libxcb-xfixes0-dev \
  libnuma-dev \
  meson \
  ninja-build \
  pkg-config \
  texinfo \
  wget \
  yasm \
  zlib1g-dev \
  libunistring-dev \
  nasm

# Build and install x264
echo "Building x264..."
cd x264 && \
PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$FFMPEG/ffmpeg_build/lib/pkgconfig" ./configure --prefix="$FFMPEG/ffmpeg_build" --bindir="$HOME/bin" --enable-static --enable-pic && \
PATH="$HOME/bin:$PATH" make -j$(nproc) && \
make install

# Build and install x265 with both 8-bit, 10-bit and 12-bit support.
echo "Building x265 with 8-bit, 10-bit, and 12-bit support..."
cd "$FFMPEG/x265_git" && \
mkdir -p build
cd build

x265_config=(
  -DCMAKE_INSTALL_PREFIX="$FFMPEG/ffmpeg_build"
  -DCMAKE_BUILD_TYPE=Release
  -DENABLE_SHARED=OFF
  -DENABLE_CLI=OFF
  -DCMAKE_ASM_NASM_FLAGS=-w-macro-params-legacy
  -DENABLE_ALPHA=ON
)

sed -i '1i#include <cstdint>' ../source/dynamicHDR10/json11/json11.cpp

mkdir 8bit 10bit 12bit
cmake "${x265_config[@]}" -DHIGH_BIT_DEPTH=ON -DEXPORT_C_API=OFF -DENABLE_HDR10_PLUS=ON -DMAIN12=ON -S ../source -B 12bit &
cmake "${x265_config[@]}" -DHIGH_BIT_DEPTH=ON -DEXPORT_C_API=OFF -DENABLE_HDR10_PLUS=ON -S ../source -B 10bit &
cmake "${x265_config[@]}" -DEXTRA_LIB="x265_main10.a;x265_main12.a" -DEXTRA_LINK_FLAGS=-L. -DLINKED_10BIT=ON -DLINKED_12BIT=ON -S ../source -B 8bit &
wait

cat >Makefile <<"EOF"
all: 12bit/libx265.a 10bit/libx265.a 8bit/libx265.a

%/libx265.a:
	$(MAKE) -C $(subst /libx265.a,,$@)

.PHONY: all
EOF

make -j$(nproc)

cd 8bit
mv ../12bit/libx265.a ../8bit/libx265_main12.a
mv ../10bit/libx265.a ../8bit/libx265_main10.a
mv libx265.a libx265_main.a

gcc-ar -M <<EOF
CREATE libx265.a
ADDLIB libx265_main.a
ADDLIB libx265_main10.a
ADDLIB libx265_main12.a
SAVE
END
EOF

make install

echo "Libs.private: -lstdc++" >> "$FFMPEG/ffmpeg_build/lib/pkgconfig/x265.pc"

# Build and install fdk-aac
echo "Building fdk-aac..."
cd "$FFMPEG/fdk-aac" && \
autoreconf -fiv && \
./configure --prefix="$FFMPEG/ffmpeg_build" --disable-shared && \
make -j$(nproc) && \
make install

# Build and install aom
echo "Building aom..."
cd "$FFMPEG/aom" && \
mkdir -p aom_build && \
cd aom_build && \
PATH="$HOME/bin:$PATH" cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$FFMPEG/ffmpeg_build" -DENABLE_TESTS=OFF -DENABLE_NASM=on .. && \
PATH="$HOME/bin:$PATH" make -j$(nproc) && \
make install

# Build and install dav1d
echo "Building dav1d..."
cd "$FFMPEG/dav1d" && \
mkdir -p build && \
cd build && \
meson setup -Denable_tools=false -Denable_tests=false --default-library=static .. --prefix "$FFMPEG/ffmpeg_build" --libdir="lib" && \
ninja && \
ninja install

# Build and install SVT-AV1
echo "Building SVT-AV1..."
cd "$FFMPEG/SVT-AV1" && \
mkdir -p build && \
cd build && \
PATH="$HOME/bin:$PATH" cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$FFMPEG/ffmpeg_build" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF .. && \
PATH="$HOME/bin:$PATH" make -j$(nproc) && \
make install

# Build and install opus
echo "Building opus..."
cd "$FFMPEG/opus" && \
./autogen.sh && \
./configure --prefix="$FFMPEG/ffmpeg_build" --disable-shared && \
make -j$(nproc) && \
make install

# Build and install libvpx
echo "Building libvpx..."
cd "$FFMPEG/libvpx" && \
PATH="$HOME/bin:$PATH" ./configure --prefix="$FFMPEG/ffmpeg_build" --disable-examples --disable-unit-tests --enable-vp9-highbitdepth --as=yasm && \
PATH="$HOME/bin:$PATH" make -j$(nproc) && \
make install

# Create output directories
mkdir -p "$FFMPEG/outputs"
mkdir -p "$FFMPEG/debuggable_outputs"

# Build and install FFmpeg
echo "Building FFmpeg..."
cd "$FFMPEG/FFmpeg" && \
PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$FFMPEG/ffmpeg_build/lib/pkgconfig" ./configure \
  --prefix="../ffmpeg_build" \
  --pkg-config-flags="--static" \
  --extra-cflags="-I$FFMPEG/ffmpeg_build/include" \
  --extra-ldflags="-L$FFMPEG/ffmpeg_build/lib" \
  --extra-libs="-lpthread -lm -lstdc++ -lnuma -lrt" \
  --ld="g++" \
  --bindir="$HOME/bin" \
  --disable-debug \
  --enable-gpl \
  --enable-gnutls \
  --enable-libaom \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libsvtav1 \
  --enable-libdav1d \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \
  --enable-nonfree && \
PATH="$HOME/bin:$PATH" make -j$(nproc) && \
make install && \
hash -r && \
cd "$FFMPEG/FFmpeg" && \
mv ffmpeg ../outputs && \
mv ffprobe ../outputs && \
mv ffplay ../outputs && \
mv ffmpeg_g ../debuggable_outputs && \
mv ffprobe_g ../debuggable_outputs && \
mv ffplay_g ../debuggable_outputs

echo "Build complete."

