name: Update Submodules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 0' # Every Sunday at 8 AM UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          token: ${{ secrets.PUSH_PAT }}

      - name: Update Submodules
        id: update_script
        run: ./update

      - name: Create Pull Request
        if: steps.update_script.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update submodules"
          title: "Update Submodules"
          body: ${{ steps.update_script.outputs.pr_body }}
          branch: "update-submodules"
          delete-branch: true

